config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get 'about', to: 'pages#about'
  get 'portfolio', to: 'pages#portfolio'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many  :articles, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def home; end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[new create update destroy]


  def index
    @articles = Article.all.order(created_at: :desc)
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      # Redirect to the article show page
      redirect_to article_path(@article), notice: 'Le nouvel article a bien été créé !'
    else
      # Render the new article form
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to @article, status: :see_other
  end

  def destroy
    set_article.user
    @article.destroy
    redirect_to articles_path, status: :see_other
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :subtitle, :content, :category)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about; end

  def portfolio; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<header>
</header>
<main>
  <section class="services">
    <div class="container blog py-5">
      <h1>Les derniers articles</h1>
      <div class="cards-articles py-5 text-justify">
        <% @articles.each do |article| %>
          <h2 class="card-title"><%= article.title %></h2>
          <p class="card-text"><%= article.subtitle%></p>
          <button type="button" class="btn btn-outline-success"><%= link_to "Lire l'article", article_path(article), class: "text-decoration-none text-color" %></button>
        <% end %>
      </div>
    </div>
  </section>
</main>

app/views/articles/new.html.erb
<header>
</header>
<main>
  <section class="article">
    <div class="container main-card py-5" >
      <div class="form-edit mb-5">
      <%= simple_form_for @article do |f| %>
          <%= f.input :title %>
          <%= f.input :subtitle %>
          <%= f.input :content,as: :text %>
          <%= f.input :category %>
          <%= f.button :submit, "Enregister l'article' !", class: "btn btn-primary" %>
      <% end %>
      </div>
    <%= link_to '< Retour aux articles', articles_path %>
    </div>
    <% if @article.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% @article.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </section>
</main>

app/views/articles/show.html.erb
<header>
</header>
<main>
  <section class="article">
    <div class="container main-card py-5" >
      <h1><%= @article.title%></h1>
      <div class="container article py-5">
        <p><%= @article.subtitle %> <br> <%= @article.content %></p>
        <p><small>Catégorie : <%= @article.category %></small></p>
      </div>
      <% if current_user == @article.user %>
      <%= link_to icon('fas', 'feather-pointed'), edit_article_path(@article), class: "btn btn-primary" %>
      <%= link_to icon('fas', 'trash-alt'), article_path(@article), class: "btn btn-danger", data: {turbo_method: :delete, turbo_confirm: "Etes-vous sûr?"}%>
      <% end %><br>
      <%= link_to '< Retour aux articles', articles_path %>
    </div>
  </section>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LESLIERDSDev</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer"%>
  </body>
</html>

app/views/pages/about.html.erb
<header class="hbg">
  <div class="container py-5">
    <div class="header">
      <div class="col-md-10">
        <div class="card-body mx-auto d-block justify">
          <h1>Je suis Leslie Rados</h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <a class="btn btn-outline-success" href="#">Me contacter</a>
          <!-- Facebook -->
          <a data-mdb-ripple-init class="btn text-white btn-floating m-1" style="background-color: #3b5998;" href="#!" role="button"><i class="fab fa-facebook-f"></i></a>
          <!-- Instagram -->
          <a data-mdb-ripple-init class="btn text-white btn-floating m-1" style="background-color: #ac2bac;" href="#!" role="button"><i class="fab fa-instagram"></i></a>
        <!-- Social media -->
        </div>
    </div>
    <div class="col-md-10 mx-auto d-block">
      <img src="https://res.cloudinary.com/ddt8brfwz/image/upload/v1712230812/Design_sans_titre_3_hhxwtx.svg" class="img-fluid rounded-start" alt="...">
    </div>
  </div>
</header>
<main>
  <section class="process">
    <div class="container py-5">
      <h1>Mon process</h1>
      <div class="cards py-5 text-justify">
        <div class="card-category"><i class="fa-solid fa-mobile-screen-button" style="color: #5705aa;"></i><br>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
        <div class="card-category"><i class="fa-solid fa-map-location-dot" style="color: #5705aa;"></i><br>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
        <div class="card-category"><i class="fa-solid fa-gears" style="color: #5705aa;"></i><br>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
      </div>
      <a class="btn btn-outline-success" href="#">En savoir +</a>
    </div>
  </section>
</main>

app/views/pages/home.html.erb
<header class="hbg">
  <div class="container py-5">
    <div class="header">
      <div class="col-md-10 center">
        <img src="https://res.cloudinary.com/ddt8brfwz/image/upload/v1712230812/Design_sans_titre_1_klokjm.svg" class="img-fluid rounded-start" alt="...">
      </div>
      <div class="col-md-10">
        <div class="card-body text-center">
          <h1>Développeuse Web</h1>
          <p>Spécialisée dans le développement de sites web et d'applications <br> pour que votre entreprise trouve sa place sur Internet</p><br>
          <a class="btn btn-outline-success" href="#">Me contacter</a>
        </div>
    </div>
  </div>
</header>
<main>
  <section class="intro">
    <div class="container main-card py-5" >
      <h1>Hello, Bonjour ! <i class="fa-solid fa-hand fa-shake" style="color: #5705aa;"></i></h1>
      <p>"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"</p>
      <a class="btn btn-outline-success" href="#">En savoir +</a>
    </div>
  </section>
  <section class="services">
    <div class="container py-5">
      <h1>Mes services</h1>
      <div class="cards py-5 text-justify">
        <div class="card-category">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
        <div class="card-category">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
        <div class="card-category">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
      </div>
      <a class="btn btn-outline-success" href="#">En savoir +</a>
    </div>
  </section>
  <section class="projets">
    <div class="container py-5">
      <h1>Projets</h1>
      <div class="card py-5">
        <div class="row g-0">
          <div class="col-md-4">
            <img src="https://res.cloudinary.com/ddt8brfwz/image/upload/v1708094756/minh-pham-lB9ylP8e9Sg-unsplash_k35xvt.jpg" class="img-fluid rounded-start" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <p class="card-text text-justify">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>
          </div>
        </div>
        <div class="row g-0">
          <div class="col-md-4">
            <img src="https://res.cloudinary.com/ddt8brfwz/image/upload/v1708094756/minh-pham-lB9ylP8e9Sg-unsplash_k35xvt.jpg" class="img-fluid rounded-start" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>
          </div>
        </div>
        <div class="row g-0">
          <div class="col-md-4">
            <img src="https://res.cloudinary.com/ddt8brfwz/image/upload/v1708094756/minh-pham-lB9ylP8e9Sg-unsplash_k35xvt.jpg" class="img-fluid rounded-start" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>
          </div>
        </div>
        <div class="row g-0">
          <div class="col-md-4">
            <img src="https://res.cloudinary.com/ddt8brfwz/image/upload/v1708094756/minh-pham-lB9ylP8e9Sg-unsplash_k35xvt.jpg" class="img-fluid rounded-start" alt="...">
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">Card title</h5>
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="contact">
    <div class="container py-5 text-center">
      <h1>Parlons de votre projet</h1>
      <h3>Prenez rendez-vous pour échanger au cours d'un moment privilégié</h3>
      <a class="btn btn-outline-success" href="#">En savoir +</a>
    </div>
  </section>
</main>

app/views/pages/portfolio.html.erb
<header class="hbg">
  <div class="container py-5">
    <div class="header">
      <div class="col-md-10 mx-auto d-block">
        <img src="https://res.cloudinary.com/ddt8brfwz/image/upload/v1712236001/Design_sans_titre_4_fuztw6.svg" class="img-fluid rounded-start" alt="...">
      </div>
      <div class="col-md-10">
        <div class="card-body mx-auto d-block justify">
          <h1>Ils m'ont fait confiance</h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <a class="btn btn-outline-success" href="#">Me contacter</a>
        </div>
    </div>
  </div>
</header>
<main>
  <section>
    <div class="container py-5">
      <h1>Clients</h1>
      <div class="card-client mb-3">
        <div class="col-md-4">
          <iframe width="560" height="315" src="https://www.youtube.com/embed/j0XA82Vhz-E?si=no0ZlFAonGQdH9he" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
      </div>
      <div class="card-client mb-3">
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
        <div class="col-md-4">
          <iframe width="560" height="315" src="https://www.youtube.com/embed/j0XA82Vhz-E?si=no0ZlFAonGQdH9he" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
        </div>
      </div>
      <div class="card-client mb-3">
        <div class="col-md-4">
          <iframe width="560" height="315" src="https://www.youtube.com/embed/j0XA82Vhz-E?si=no0ZlFAonGQdH9he" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
          </div>
        </div>
      </div>
    </div>
  </section>
</main>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-body-tertiary text-center">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a
      data-mdb-ripple-init
        class="btn text-white btn-floating m-1"
        style="background-color: #3b5998;"
        href="#!"
        role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Instagram -->
      <a
        data-mdb-ripple-init
        class="btn text-white btn-floating m-1"
        style="background-color: #ac2bac;"
        href="#!"
        role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a
        data-mdb-ripple-init
        class="btn text-white btn-floating m-1"
        style="background-color: #0082ca;"
        href="#!"
        role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>
      <!-- Github -->
      <a
        data-mdb-ripple-init
        class="btn text-white btn-floating m-1"
        style="background-color: #333333;"
        href="#!"
        role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
      Un site réalisé avec <i class="fa-solid fa-heart fa-bounce" style="color: #5705aa;"></i><br>
    © 2024 tous droits réservés:
    <a class="text-body" href="">LeslieRds.dev</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_navbar.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <!-- logo -->
    <a class="navbar-brand" href="#"><img src="https://res.cloudinary.com/ddt8brfwz/image/upload/v1712159438/Black_And_White_Aesthetic_Minimalist_Modern_Simple_Typography_Coconut_Cosmetics_Logo_4_lu7xzv.png" alt="Logo Leslie Rds" width="250" ></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCenteredContent" aria-controls="navbarCenteredContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- menu -->
    <div class="collapse navbar-collapse justify-content-center" id="navbarCenteredContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Accueil</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/about">A Propos</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/portfolio">Portfolio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/articles">Blog</a>
        </li>
    </div>
    <!-- bouton -->
    <div class="d-flex">
      <button class="btn btn-outline-success" href="https://calendly.com/leslie-rados-hyds/rdv-de-decouverte-de-votre-projet" type="submit">Contact</button>
    </div>
  </div>
</nav>